# Generated by Django 2.0.6 on 2018-06-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlserver', '0002_auto_20180618_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_owner', to='graphqlserver.Customer'),
        ),
    ]
