# Generated by Django 2.0.6 on 2018-06-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlserver', '0003_auto_20180618_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plan_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Travler', 'Travler'), ('Weekly', 'Weekly')], default='MONTHLY', max_length=9),
        ),
    ]
